using System;
using System.Collections.Generic;

namespace VK.Blocks.AI.Cognitive;

/// <summary>
/// Represents a proactive goal or task generated by the AI engine.
/// </summary>
public sealed record VKAIGoal // [AP.01]
{
    /// <summary>
    /// Gets the unique identifier for the goal.
    /// </summary>
    public required Guid Id { get; init; }

    /// <summary>
    /// Gets the title or short description of the goal.
    /// </summary>
    public required string Title { get; init; }

    /// <summary>
    /// Gets the detailed description of what the AI intends to do.
    /// </summary>
    public string? Description { get; init; }

    /// <summary>
    /// Gets the priority of the goal.
    /// </summary>
    public int Priority { get; init; } = 0;

    /// <summary>
    /// Gets the signal that triggered this goal.
    /// </summary>
    /// <remarks>
    /// In industrial use, this maps to signals from VK.Blocks.AI.Somatic.
    /// </remarks>
    public string TriggeringSignal { get; init; } = "None";

    /// <summary>
    /// Gets additional context or data required for the goal.
    /// </summary>
    public IReadOnlyDictionary<string, object> Context { get; init; } = new Dictionary<string, object>();

    /// <summary>
    /// Gets when the goal was created.
    /// </summary>
    public required DateTimeOffset CreatedAt { get; init; }
}
