namespace VK.Blocks.VectorIngest;

/// <summary>
/// Extension methods for chaining AI Ingest features.
/// </summary>
/// <remarks>
/// This is a partial class. Standard features (such as AddVKDocumentLoader, AddVKPipeline, etc.)
/// are automatically generated by the VK.Feature source generator.
/// Custom or non-standard registration extensions should be manually implemented in this file.
/// </remarks>
public static partial class VKVectorIngestBuilderExtensions
{
    // [Anchor] Add your custom, non-automated extension methods here.
}
