namespace VK.Blocks.AI.Psyche;

/// <summary>
/// Extension methods for chaining AI Psyche features.
/// </summary>
/// <remarks>
/// This is a partial class. Standard features (such as AddVKDirective, AddVKEcho, and AddVKAIPsycheDefaultFeatures)
/// are automatically generated by the VK.Feature source generator.
/// Custom or non-standard registration extensions should be manually implemented in this file.
/// </remarks>
public static partial class VKAIPsycheBuilderExtensions
{
    // [Anchor] Add your custom, non-automated extension methods here.
}
