namespace VK.Blocks.Web.Diagnostics.Internal;

/// <summary>
/// Constants for Web diagnostics.
/// </summary>
internal static class WebDiagnosticsConstants
{
    public static readonly string SourceName = VKWebBlock.Instance.ActivitySourceName;

    // Metrics
    public const string RequestCounterName = "vk.web.requests.total";
    public const string RequestCounterDescription = "Total number of HTTP requests processed by VK middleware.";

    public const string RequestActiveName = "vk.web.requests.active";
    public const string RequestActiveDescription = "Number of active HTTP requests currently being processed.";

    public const string CorrelationIdCounterName = "vk.web.correlation_id.assigned";
    public const string CorrelationIdCounterDescription = "Number of times a new Correlation ID was assigned.";

    public const string RequestDurationName = "vk.web.requests.duration";
    public const string RequestDurationDescription = "The duration of HTTP requests processed by VK middleware.";

    public const string RequestSizeName = "vk.web.requests.size";
    public const string RequestSizeDescription = "The size of HTTP request bodies in bytes.";

    public const string ResponseSizeName = "vk.web.responses.size";
    public const string ResponseSizeDescription = "The size of HTTP response bodies in bytes.";

    public const string ErrorCounterName = "vk.web.errors.total";
    public const string ErrorCounterDescription = "Total number of error responses generated by the web block.";

    // Tags
    public const string TagMethod = "http.method";
    public const string TagStatusCode = "http.status_code";
    public const string TagPath = "http.target";
    public const string TagRequestSize = "http.request_content_length";
    public const string TagResponseSize = "http.response_content_length";
    public const string TagErrorType = "vk.error.type";
    public const string TagErrorCode = "vk.error.code";
    public const string TagExceptionType = "exception.type";
    public const string TagTenantId = "vk.tenant.id";

    // Activities
    public const string ActivityHandleException = "Handle Exception";
    public const string ActivityCorrelationId = "CorrelationId Middleware";
    public const string ActivityTenancy = "Tenancy Middleware";
    public const string ActivityDiagnostics = "Diagnostics Middleware";
    public const string ActivityRequestLogging = "RequestLogging Middleware";
    public const string HttpStatusCodeTagName = "http.status_code";
}
