using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VK.Tools.SourceGenerators.Domain;

/// <summary>
/// Incremental Source Generator that produces zero-reflection FastToString and FastTryParse extensions for enums.
/// </summary>
[Generator]
public sealed class VKEnumExtensionsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enumDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is EnumDeclarationSyntax,
                transform: static (ctx, _) => (EnumDeclarationSyntax)ctx.Node)
            .Where(static m => m is not null);

        var compilationAndEnums = context.CompilationProvider.Combine(enumDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndEnums, static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(Compilation compilation, ImmutableArray<EnumDeclarationSyntax> enums, SourceProductionContext context)
    {
        if (enums.IsDefaultOrEmpty)
        {
            return;
        }

        foreach (var enumDeclaration in enums.Distinct())
        {
            var semanticModel = compilation.GetSemanticModel(enumDeclaration.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(enumDeclaration) is not INamedTypeSymbol enumSymbol)
            {
                continue;
            }

            var ns = enumSymbol.ContainingNamespace.IsGlobalNamespace ? null : enumSymbol.ContainingNamespace.ToDisplayString();
            var enumName = enumSymbol.Name;
            var members = enumSymbol.GetMembers().OfType<IFieldSymbol>().Where(f => f.ConstantValue is not null).ToList();

            if (members.Count == 0)
            {
                continue;
            }

            var source = GenerateEnumExtensions(ns, enumName, members);
            context.AddSource($"{enumName}Extensions.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateEnumExtensions(string? ns, string enumName, List<IFieldSymbol> members)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"public static partial class {enumName}Extensions");
        sb.AppendLine("{");

        // 1. FastToString (Switch expression - zero reflection)
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Fast, zero-allocation string representation of <see cref=\"{enumName}\"/>.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static string FastToString(this {enumName} value) => value switch");
        sb.AppendLine("    {");
        foreach (var member in members)
        {
            sb.AppendLine($"        {enumName}.{member.Name} => nameof({enumName}.{member.Name}),");
        }
        sb.AppendLine($"        _ => value.ToString()");
        sb.AppendLine("    };");
        sb.AppendLine();

        // 2. FastTryParse
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Fast, case-insensitive parse for <see cref=\"{enumName}\"/> without reflection.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public static bool FastTryParse(string? value, out {enumName} result)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (value)");
        sb.AppendLine("        {");
        foreach (var member in members)
        {
            sb.AppendLine($"            case string s when string.Equals(s, nameof({enumName}.{member.Name}), System.StringComparison.OrdinalIgnoreCase):");
            sb.AppendLine($"                result = {enumName}.{member.Name};");
            sb.AppendLine("                return true;");
        }
        sb.AppendLine("            default:");
        sb.AppendLine($"                result = default;");
        sb.AppendLine("                return false;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }
}
