using System.Text;

namespace VK.Blocks.Generators.Extensions;

/// <summary>
/// Provides utility methods for building generated source code with a consistent structure.
/// </summary>
internal static class SourceCodeBuilder
{
    private const string AutoGeneratedHeader = @"// <auto-generated/>
#nullable enable

";

    /// <summary>
    /// Creates a new <see cref="StringBuilder"/> with the standard auto-generated header.
    /// </summary>
    /// <returns>A new <see cref="StringBuilder"/> containing the auto-generated header.</returns>
    public static StringBuilder CreateWithHeader()
    {
        return new StringBuilder(AutoGeneratedHeader);
    }

    /// <summary>
    /// Appends the standard auto-generated header to an existing <see cref="StringBuilder"/>.
    /// </summary>
    /// <param name="sb">The <see cref="StringBuilder"/> to append the header to.</param>
    public static void AppendHeader(StringBuilder sb)
    {
        sb.Append(AutoGeneratedHeader);
    }
}
