namespace VK.Blocks.AI.Corpus;

/// <summary>
/// Chained builder extension methods for configuring individual features within the AI.Corpus block.
/// </summary>
/// <remarks>
/// This is a partial class. Standard features (such as AddVKGathering, AddVKFiltering, etc.)
/// are automatically generated by the VK.Feature source generator.
/// Custom or non-standard registration extensions should be manually implemented in this file.
/// </remarks>
public static partial class VKAICorpusBuilderExtensions
{
    // [Anchor] Add your custom, non-automated extension methods here.
}
