namespace VK.Blocks.VectorSearch;

/// <summary>
/// Extension methods for configuring sub-features on the vector search builder.
/// </summary>
/// <remarks>
/// This is a partial class. Standard features (such as AddVKSemanticCache, AddVKVectorReranking, etc.)
/// are automatically generated by the VK.Feature source generator.
/// Custom or non-standard registration extensions should be manually implemented in this file.
/// </remarks>
public static partial class VKVectorSearchBuilderExtensions
{
    // [Anchor] Add your custom, non-automated extension methods here.
}
