using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using VK.Tools.SourceGenerators.Extensions;

namespace VK.Tools.SourceGenerators.Persist;

/// <summary>
/// Incremental Source Generator that automatically emits an <see cref="IVKModelConventionContributor"/>
/// and an <see cref="IVKModelCreatingContributor"/> for any assembly declaring [VKPersistEntity] classes,
/// discovering strongly-typed IDs and registering their EF Core conversions dynamically.
/// </summary>
[Generator]
public sealed class VKPersistConventionGenerator : IIncrementalGenerator
{
    private const string PersistEntityAttributeFullName = "VK.Blocks.Core.VKPersistEntityAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var entities = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                PersistEntityAttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
            .Collect();

        var compilationAndEntities = context.CompilationProvider.Combine(entities);

        context.RegisterSourceOutput(compilationAndEntities, static (ctx, source) =>
        {
            var (compilation, entityList) = source;
            if (entityList.IsEmpty) return;

            EmitContributor(ctx, compilation, entityList);
        });
    }

    private static void EmitContributor(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> entities)
    {
        var assemblyName = compilation.AssemblyName ?? "VK.Generated";
        var safePrefix = new string(assemblyName.Where(char.IsLetterOrDigit).ToArray());
        var rootNamespace = entities.FirstOrDefault()?.ContainingNamespace.ToDisplayString() ?? "VK.Generated";

        // Find all strongly-typed IDs used across the entities (properties and key types)
        var stronglyTypedIds = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var entity in entities)
        {
            var members = entity.GetMembers().OfType<IPropertySymbol>();
            foreach (var prop in members)
            {
                CheckAndAddStronglyTypedId(prop.Type, stronglyTypedIds);
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore.Storage.ValueConversion;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using VK.Blocks.Core;");
        sb.AppendLine("using VK.Blocks.Persistence.EFCore;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Auto-generated Model and Convention Contributor for {assemblyName}.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = \"Auto-generated EF Core model and convention contributor.\")]");
        sb.AppendLine($"internal sealed partial class {safePrefix}ModelContributor : IVKModelCreatingContributor, IVKModelConventionContributor");
        sb.AppendLine("{");
        sb.AppendLine("    public void ConfigureModel(ModelBuilder modelBuilder)");
        sb.AppendLine("    {");
        sb.AppendLine("        VKGuard.NotNull(modelBuilder);");
        sb.AppendLine($"        modelBuilder.ApplyConfigurationsFromAssembly(typeof({safePrefix}ModelContributor).Assembly);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)");
        sb.AppendLine("    {");
        sb.AppendLine("        VKGuard.NotNull(configurationBuilder);");

        foreach (var idType in stronglyTypedIds.OrderBy(t => t.Name))
        {
            var fullTypeName = idType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var converterName = $"{idType.Name}AutoEfCoreConverter";
            sb.AppendLine($"        configurationBuilder.Properties<{fullTypeName}>().HaveConversion<{converterName}>();");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // Emit private nested converters for each discovered strongly-typed ID
        foreach (var idType in stronglyTypedIds.OrderBy(t => t.Name))
        {
            var fullTypeName = idType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var converterName = $"{idType.Name}AutoEfCoreConverter";
            sb.AppendLine($"    private sealed class {converterName}() : ValueConverter<{fullTypeName}, Guid>(id => id.Value, value => new {fullTypeName}(value));");
        }

        sb.AppendLine("}");
        sb.AppendLine();

        // Extension method to register into IServiceCollection
        sb.AppendLine($"public static class {safePrefix}ModelContributorExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IServiceCollection AddGeneratedModelContributors(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.TryAddEnumerable(ServiceDescriptor.Singleton<IVKModelCreatingContributor, {safePrefix}ModelContributor>());");
        sb.AppendLine($"        services.TryAddEnumerable(ServiceDescriptor.Singleton<IVKModelConventionContributor, {safePrefix}ModelContributor>());");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{safePrefix}ModelContributor.g.cs", sb.ToString());
    }

    private static void CheckAndAddStronglyTypedId(ITypeSymbol type, HashSet<ITypeSymbol> result)
    {
        var unwrapped = type;
        if (unwrapped is INamedTypeSymbol { IsGenericType: true, ConstructedFrom.SpecialType: SpecialType.System_Nullable_T } nullableType)
        {
            unwrapped = nullableType.TypeArguments[0];
        }

        if (unwrapped is INamedTypeSymbol namedType)
        {
            // Check if annotated with [VKStronglyTypedId] or has 'Value' property of type Guid
            var hasAttr = namedType.GetAttributes().Any(a =>
                a.AttributeClass?.Name is "VKStronglyTypedIdAttribute" or "VKStronglyTypedId");

            var hasGuidValue = namedType.GetMembers("Value").OfType<IPropertySymbol>().Any(p =>
                p.Type.ToDisplayString() == "System.Guid" || p.Type.Name == "Guid");

            if (hasAttr || hasGuidValue)
            {
                result.Add(namedType);
            }
        }
    }
}
