using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ModelContextProtocol.Server;
using Regex = System.Text.RegularExpressions.Regex;

namespace VK.Tools.McpServer.Internal;

internal sealed partial class McpTools
{
    [McpServerTool]
    [Description("Executes code coverage analysis for a specific test project using dotnet test and reportgenerator. Returns the summary.")]
    public static async Task<string> VKBeExecuteCoverageAnalysis(
        [Description("Path to the test project file (.csproj) or directory.")] string projectPath,
        [Description("Build configuration (Debug/Release).")] string configuration = "Release",
        [Description("Whether to perform a deep clean before testing.")] bool clean = false,
        [Description("Comma-separated list of report types (e.g. 'Html;TextSummary;JsonSummary').")] string reportTypes = "Html;TextSummary",
        CancellationToken ct = default)
    {
        try
        {
            var projectRoot = FindProjectRoot();
            var scriptPath = Path.Combine(projectRoot, "prompts", "HitoriGoto", "dotnettest.ps1");

            if (!File.Exists(scriptPath))
            {
                return $"[Error] Coverage script not found at: {scriptPath}";
            }

            var args = $"-ExecutionPolicy Bypass -File \"{scriptPath}\" -Project \"{projectPath}\" -Configuration \"{configuration}\" -ReportTypes \"{reportTypes}\" -NoBrowser";
            if (clean)
            {
                args += " -Clean";
            }

            var startInfo = new ProcessStartInfo
            {
                FileName = "powershell.exe",
                Arguments = args,
                WorkingDirectory = projectRoot,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            using var process = Process.Start(startInfo);
            if (process == null)
                return "[Error] Failed to start powershell process.";

            var stdoutTask = process.StandardOutput.ReadToEndAsync(ct);
            var stderrTask = process.StandardError.ReadToEndAsync(ct);

            await process.WaitForExitAsync(ct).ConfigureAwait(false);

            var stdout = await stdoutTask.ConfigureAwait(false);
            var stderr = await stderrTask.ConfigureAwait(false);

            if (process.ExitCode != 0)
            {
                return $"[Error] Coverage analysis failed (ExitCode: {process.ExitCode}):\n{stderr}\n{stdout}";
            }

            return $"Coverage Analysis Result for {projectPath}:\n\n{stdout}";
        }
        catch (Exception ex)
        {
            return $"[Error] Coverage analysis failed: {ex.Message}";
        }
    }

    [McpServerTool]
    [Description("Parses a coverage summary file and suggests improvements (Exclude vs Test) based on file content analysis.")]
    public static async Task<string> VKBeAuditCoverageCompliance(
        [Description("Path to the Summary.txt generated by reportgenerator.")] string summaryPath,
        CancellationToken ct)
    {
        try
        {
            var projectRoot = FindProjectRoot();
            var absPath = Path.IsPathRooted(summaryPath) ? summaryPath : Path.Combine(projectRoot, summaryPath);

            if (!File.Exists(absPath))
            {
                return $"[Error] Summary file not found at: {absPath}";
            }

            var content = await File.ReadAllLinesAsync(absPath, ct).ConfigureAwait(false);
            var gaps = new List<(string ClassName, double Coverage)>();

            // Regex for "  ClassName   Coverage%"
            var regex = new Regex(@"^\s+(VK\.Blocks\.[\w\.]+)\s+(\d+\.?\d*)%");

            foreach (var line in content)
            {
                if (line.Contains("VK.Blocks.", StringComparison.OrdinalIgnoreCase))
                {
                    var match = regex.Match(line);
                    if (match.Success)
                    {
                        var className = match.Groups[1].Value;
                        if (double.TryParse(match.Groups[2].Value, out var coverage) && coverage < 90.0)
                        {
                            gaps.Add((className, coverage));
                        }
                    }
                }
            }

            if (gaps.Count == 0)
            {
                return "[MCP Tool: VKAuditCoverageCompliance]\nSUCCESS: All classes meet the 90% coverage threshold.";
            }

            var gapList = string.Join("\n", gaps.Select(g => $"- {g.ClassName} ({g.Coverage}%)"));
            return $"[MCP Tool: VKAuditCoverageCompliance]\nFound {gaps.Count} classes with coverage below 90%.\n\nGAP ANALYSIS:\n{gapList}\n\nYOUR TASK (based on vk-coverage-optimization.md):\nFor each class above, perform a \"Deep Audit\":\n1. READ the source code of the class.\n2. CATEGORIZE:\n   - **Infrastructure/Boilerplate**: Suggest adding `[ExcludeFromCodeCoverage]` with professional justification.\n   - **Business Logic**: Suggest generating unit tests focusing on uncovered paths.\n3. OUTPUT a structured execution plan.";
        }
        catch (Exception ex)
        {
            return $"[Error] Failed to audit coverage gaps: {ex.Message}";
        }
    }
}

