using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using VK.Blocks.Generators.Extensions;

namespace VK.Blocks.Generators.Authorization;

[Generator]
public sealed class AuthorizationHandlersGenerator : IIncrementalGenerator
{
    private const string _handlerInterfaceName = "IAuthorizationHandler";
    private const string _vkHandlerInterfaceName = "IVKAuthorizationHandler";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: IsLikelyHandlerClass,
                transform: GetHandlerInfoForSourceGen)
            .WhereNotNull();

        context.RegisterSourceOutput(handlers.Collect(), (spc, collectedHandlers) => Execute(spc, collectedHandlers));
    }

    private static bool IsLikelyHandlerClass(SyntaxNode node, System.Threading.CancellationToken _)
    {
        if (node is ClassDeclarationSyntax classDeclaration && classDeclaration.BaseList is not null)
        {
            foreach (var baseType in classDeclaration.BaseList.Types)
            {
                var typeName = baseType.Type.ToString();
                if (typeName.Contains("AuthorizationHandler"))
                {
                    return true;
                }
            }
        }
        return false;
    }

    private static HandlerInfo? GetHandlerInfoForSourceGen(
        GeneratorSyntaxContext context,
        System.Threading.CancellationToken _)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        // Skip abstract classes
        if (classDeclaration.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.AbstractKeyword)))
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        var implementsAspNetHandler = false;
        var implementsVKHandler = false;

        // Check implemented interfaces
        foreach (var iface in classSymbol.AllInterfaces)
        {
            if (iface.Name == _handlerInterfaceName)
            {
                implementsAspNetHandler = true;
            }
            else if (iface.Name == _vkHandlerInterfaceName)
            {
                implementsAspNetHandler = true;
                implementsVKHandler = true;
            }
        }

        // Check base classes (e.g. AuthorizationHandler<T>)
        var baseType = classSymbol.BaseType;
        while (baseType != null)
        {
            if (baseType.Name.StartsWith("AuthorizationHandler"))
            {
                implementsAspNetHandler = true;
                break;
            }
            baseType = baseType.BaseType;
        }

        if (implementsAspNetHandler || implementsVKHandler)
        {
            return new HandlerInfo(classSymbol.ToDisplayString(), implementsVKHandler);
        }

        return null;
    }

    private static void Execute(SourceProductionContext context, System.Collections.Immutable.ImmutableArray<HandlerInfo> handlers)
    {
        if (handlers.IsDefaultOrEmpty)
        {
            return;
        }

        var handlersToRegister = handlers
            .GroupBy(h => h.ImplementationName)
            .Select(g => new HandlerInfo(
                g.Key,
                g.Any(h => h.IsVKHandler)))
            .ToList();

        if (handlersToRegister.Count == 0)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;"); // 引入 TryAddEnumerable
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine();

        sb.AppendLine("namespace VK.Blocks.Authorization.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static class GeneratedAuthorizationServiceCollectionExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Scans and automatically registers all classes implementing IAuthorizationHandler or IVKAuthorizationHandler.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddGeneratedAuthorizationHandlers(this IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var handler in handlersToRegister)
        {
            var implName = handler.ImplementationName;
            var isVKHandler = handler.IsVKHandler;

            if (isVKHandler)
            {
                sb.AppendLine($"            services.TryAddEnumerable(ServiceDescriptor.Scoped<VK.Blocks.Authorization.Abstractions.IVKAuthorizationHandler, {implName}>());");
            }
            sb.AppendLine($"            services.TryAddEnumerable(ServiceDescriptor.Scoped<IAuthorizationHandler, {implName}>());");
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedAuthorizationServiceCollectionExtensions.g.cs", Microsoft.CodeAnalysis.Text.SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record HandlerInfo(string ImplementationName, bool IsVKHandler);
}
