using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using VK.Blocks.Generators.Authorization.Internal;
using VK.Blocks.Generators.Extensions;
using VK.Blocks.Generators.Utilities;

namespace VK.Blocks.Generators.Authorization;

[Generator]
public sealed class AuthorizationHandlersGenerator : IIncrementalGenerator
{
    private const string HandlerInterfaceName = "IAuthorizationHandler";
    private const string PermissionEvaluatorInterfaceName = "IPermissionEvaluator";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: IsLikelyHandlerClass,
                transform: GetHandlerInfoForSourceGen)
            .WhereNotNull();

        var assemblyName = context.CompilationProvider.Select(static (c, _) => c.AssemblyName);
        var combined = handlers.Collect().Combine(assemblyName);

        context.RegisterSourceOutput(combined, (spc, pair) => Execute(spc, pair.Left, pair.Right, this.GetType()));
    }

    private static bool IsLikelyHandlerClass(SyntaxNode node, System.Threading.CancellationToken _)
    {
        if (node is ClassDeclarationSyntax classDeclaration && classDeclaration.BaseList is not null)
        {
            foreach (var baseType in classDeclaration.BaseList.Types)
            {
                var typeName = baseType.Type.ToString();
                if (typeName.Contains("AuthorizationHandler") || typeName.Contains(PermissionEvaluatorInterfaceName))
                {
                    return true;
                }
            }
        }
        return false;
    }

    private static HandlerInfo? GetHandlerInfoForSourceGen(
        GeneratorSyntaxContext context,
        System.Threading.CancellationToken _)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        // Skip abstract classes
        if (classDeclaration.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.AbstractKeyword)))
        {
            return null;
        }

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        var implementsAspNetHandler = false;
        var implementsPermissionEvaluator = false;

        // Check implemented interfaces
        foreach (var iface in classSymbol.AllInterfaces)
        {
            if (iface.Name == HandlerInterfaceName)
            {
                implementsAspNetHandler = true;
            }
            else if (iface.Name == PermissionEvaluatorInterfaceName)
            {
                implementsPermissionEvaluator = true;
            }
        }

        // Check base classes (e.g. AuthorizationHandler<T>)
        var baseType = classSymbol.BaseType;
        while (baseType != null)
        {
            if (baseType.Name.StartsWith("AuthorizationHandler"))
            {
                implementsAspNetHandler = true;
                break;
            }
            baseType = baseType.BaseType;
        }

        if (implementsAspNetHandler || implementsPermissionEvaluator)
        {
            return new HandlerInfo(classSymbol.ToDisplayString(), implementsPermissionEvaluator);
        }

        return null;
    }

    private static void Execute(SourceProductionContext context, System.Collections.Immutable.ImmutableArray<HandlerInfo> handlers, string? assemblyName, Type generatorType)
    {
        // Guard against execution in unrelated assemblies
        if (!VKBlockGeneratorGuard.ShouldExecute(generatorType, assemblyName))
        {
            return;
        }

        if (handlers.IsDefaultOrEmpty)
        {
            return;
        }

        var handlersToRegister = handlers
            .GroupBy(h => h.ImplementationName)
            .Select(g => new HandlerInfo(
                g.Key,
                g.Any(h => h.IsPermissionEvaluator)))
            .ToList();

        if (handlersToRegister.Count == 0)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine();

        sb.AppendLine("namespace VK.Blocks.Authorization.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static class GeneratedAuthorizationServiceCollectionExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Scans and automatically registers all classes implementing IAuthorizationHandler or IPermissionEvaluator.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddGeneratedAuthorizationHandlers(this IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var handler in handlersToRegister)
        {
            var implName = handler.ImplementationName;
            var isEvaluator = handler.IsPermissionEvaluator;

            if (isEvaluator)
            {
                sb.AppendLine($"            services.TryAddEnumerable(ServiceDescriptor.Scoped<VK.Blocks.Authorization.Features.Permissions.IPermissionEvaluator, {implName}>());");
            }

            // Standard AuthorizationHandler registration
            sb.AppendLine($"            services.TryAddEnumerable(ServiceDescriptor.Scoped<IAuthorizationHandler, {implName}>());");
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedAuthorizationServiceCollectionExtensions.g.cs", Microsoft.CodeAnalysis.Text.SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
