using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using VK.Blocks.Generators.Extensions;

namespace VK.Blocks.Generators.Authorization;

/// <summary>
/// Scans for enums decorated with [GenerateRankAuthorize] and generates
/// corresponding Authorization Policies and AuthorizeAttributes.
/// </summary>
[Generator]
public sealed class MinimumRankGenerator : IIncrementalGenerator
{
    private const string _attributeName = "GenerateRankAuthorize";
    private const string _attributeFullName = "VK.Blocks.Authorization.Abstractions." + _attributeName;

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enumInfos = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is EnumDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: GetRankEnumInfo)
            .WhereNotNull();

        context.RegisterSourceOutput(enumInfos.Collect(), Execute);
    }

    private static RankEnumInfo? GetRankEnumInfo(GeneratorSyntaxContext context, System.Threading.CancellationToken ct)
    {
        var enumDeclaration = (EnumDeclarationSyntax)context.Node;

        foreach (var attributeList in enumDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (context.SemanticModel.GetSymbolInfo(attribute, ct).Symbol is not IMethodSymbol attributeSymbol)
                {
                    continue;
                }

                var attributeContainingTypeSymbol = attributeSymbol.ContainingType;
                var fullName = attributeContainingTypeSymbol.ToDisplayString();

                if (fullName == _attributeFullName || fullName == _attributeFullName + "Attribute")
                {
                    if (context.SemanticModel.GetDeclaredSymbol(enumDeclaration) is not INamedTypeSymbol enumSymbol)
                    {
                        return null;
                    }

                    var members = enumSymbol.GetMembers()
                        .OfType<IFieldSymbol>()
                        .Select(m => m.Name)
                        .ToList();

                    return new RankEnumInfo(
                        enumSymbol.ContainingNamespace.ToDisplayString(),
                        enumSymbol.Name,
                        members);
                }
            }
        }

        return null;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<RankEnumInfo> enums)
    {
        if (enums.IsDefaultOrEmpty)
        {
            return;
        }

        foreach (var info in enums.Distinct())
        {
            GenerateCode(context, info);
        }
    }

    private static void GenerateCode(SourceProductionContext context, RankEnumInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine();
        sb.AppendLine("namespace VK.Blocks.Authorization.Generated");
        sb.AppendLine("{");

        // 1. Generate RankPolicies constants
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Authorization policy names generated from <see cref=\"{info.Namespace}.{info.Name}\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class RankPolicies");
        sb.AppendLine("    {");
        foreach (var memberName in info.Members)
        {
            sb.AppendLine($"        public const string {memberName}AndAbove = \"{memberName}AndAbove\";");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // 2. Generate MinimumRankAttribute
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Marks a controller or action as requiring at least a specific <see cref=\"{info.Namespace}.{info.Name}\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Method, AllowMultiple = false)]");
        sb.AppendLine($"    public sealed class MinimumRankAttribute : AuthorizeAttribute");
        sb.AppendLine("    {");
        sb.AppendLine($"        public {info.Namespace}.{info.Name} Rank {{ get; }}");
        sb.AppendLine();
        sb.AppendLine($"        public MinimumRankAttribute({info.Namespace}.{info.Name} rank)");
        sb.AppendLine("        {");
        sb.AppendLine("            Rank = rank;");
        sb.AppendLine("            Policy = rank switch");
        sb.AppendLine("            {");
        foreach (var memberName in info.Members)
        {
            sb.AppendLine($"                {info.Namespace}.{info.Name}.{memberName} => RankPolicies.{memberName}AndAbove,");
        }
        sb.AppendLine("                _ => throw new System.ArgumentOutOfRangeException(nameof(rank))");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        context.AddSource($"{info.Name}.g.cs", Microsoft.CodeAnalysis.Text.SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record RankEnumInfo(string Namespace, string Name, List<string> Members);
}
