using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using VK.Blocks.Generators.Extensions;

namespace VK.Blocks.Generators.Authorization;

[Generator]
public sealed class PermissionsCatalogGenerator : IIncrementalGenerator
{
    private const string TargetAttributeName = "AuthorizePermission";
    private const string TargetRolesAttributeName = "AuthorizeRoles";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var permissionAttributes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: IsTargetAttribute,
                transform: GetPermissionString)
            .Where(x => !string.IsNullOrEmpty(x));

        context.RegisterSourceOutput(permissionAttributes.Collect(), Execute);
    }

    private static bool IsTargetAttribute(SyntaxNode node, System.Threading.CancellationToken _)
    {
        if (node is AttributeSyntax attributeSyntax)
        {
            var name = attributeSyntax.Name.ToString();
            // Match AuthorizePermission or AuthorizePermissionAttribute
            return name.Contains(TargetAttributeName) || name.Contains(TargetRolesAttributeName);
        }
        return false;
    }

    private static string? GetPermissionString(GeneratorSyntaxContext context, System.Threading.CancellationToken _)
    {
        var attributeSyntax = (AttributeSyntax)context.Node;

        if (attributeSyntax.ArgumentList is null || attributeSyntax.ArgumentList.Arguments.Count == 0)
        {
            return null;
        }

        // Extremely simplified extraction for constants or literals used in the attribute constructor.
        // E.g., [AuthorizePermission("Users.Read")]
        foreach (var argument in attributeSyntax.ArgumentList.Arguments)
        {
            if (argument.Expression is LiteralExpressionSyntax literalExpression &&
                literalExpression.Token.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.StringLiteralToken))
            {
                return literalExpression.Token.ValueText;
            }
        }

        return null;
    }

    private static void Execute(
        SourceProductionContext context,
        System.Collections.Immutable.ImmutableArray<string?> permissions)
    {
        if (permissions.IsDefaultOrEmpty)
        {
            return;
        }

        var uniquePermissions = permissions.Distinct().OrderBy(p => p).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace VK.Blocks.Authorization.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Strongly-typed catalog of all permissions discovered via [AuthorizePermission] and [AuthorizeRoles] attributes.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class PermissionsCatalog");
        sb.AppendLine("    {");

        foreach (var permission in uniquePermissions)
        {
            // Clean up the string to form a valid C# identifier
            var safeName = new string(permission.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());

            // Capitalize first letter if it's lowercase, just to be neat
            if (safeName.Length > 0 && char.IsLower(safeName[0]))
            {
                safeName = char.ToUpper(safeName[0]) + safeName.Substring(1);
            }

            // Ensure it doesn't start with a number
            if (safeName.Length > 0 && char.IsDigit(safeName[0]))
            {
                safeName = "_" + safeName;
            }

            sb.AppendLine($"        public const string {safeName} = \"{permission}\";");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("PermissionsCatalog.g.cs", Microsoft.CodeAnalysis.Text.SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
