// <auto-generated/>
// Polyfill required so that C# records and init-only setters work on netstandard2.0.
// The compiler synthesises the IsExternalInit attribute at the call-site,
// but the type itself must exist in the target framework.

namespace System.Runtime.CompilerServices
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    internal static class IsExternalInit { }
}
