using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.DependencyInjection;
using VK.Blocks.Authorization.Abstractions;
using VK.Blocks.Authorization.Features.DynamicPolicies;
using VK.Blocks.Authorization.Features.Permissions;
using VK.Blocks.Authorization.Generated;

namespace VK.Blocks.Authorization.DependencyInjection;

/// <summary>
/// Service collection extensions for VK.Blocks.Authorization module.
/// </summary>
public static class AuthorizationServiceCollectionExtensions
{
    #region Public Methods

    /// <summary>
    /// Adds VK authorization services to the specified <see cref="IServiceCollection"/>.
    /// </summary>
    public static IServiceCollection AddVKAuthorization(this IServiceCollection services)
    {
        services.AddScoped<IAttributeEvaluator, AttributeEvaluator>();

        // Auto-register all IAuthorizationHandler and IVKAuthorizationHandler implementations
        // generated by VK.Blocks.Generators.Authorization.AuthorizationHandlersGenerator
        services.AddGeneratedAuthorizationHandlers();

        // Dynamic Policy Provider
        services.AddSingleton<IAuthorizationPolicyProvider, PermissionPolicyProvider>();

        return services;
    }

    #endregion
}




