using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using VK.Blocks.Authorization.Features.Permissions.Metadata;
using VK.Blocks.Core.Results;
using VK.Blocks.Core.Utilities.State;

namespace VK.Blocks.Authorization.Features.Permissions.Persistence;

/// <summary>
/// Provides extension methods for <see cref="IPermissionStore"/> to simplify synchronization orchestration.
/// </summary>
public static class PermissionStoreExtensions
{
    private const string SyncKey = "VK_Authorization_Permissions";

    /// <summary>
    /// Synchronizes permissions only if the provided <paramref name="currentHash"/> differs from the last stored hash in the state store.
    /// </summary>
    /// <param name="store">The domain-specific permission store.</param>
    /// <param name="stateStore">The generic synchronization state store.</param>
    /// <param name="permissions">The collection of permissions to sync.</param>
    /// <param name="currentHash">The current metadata hash generated by the source generator.</param>
    /// <param name="ct">A cancellation token.</param>
    /// <returns>A result indicating the outcome of the operation.</returns>
    public static async ValueTask<Result> SyncIfChangedAsync(
        this IPermissionStore store,
        ISyncStateStore stateStore,
        IEnumerable<Permission> permissions,
        string currentHash,
        CancellationToken ct = default)
    {
        var lastHash = await stateStore.GetLastHashAsync(SyncKey, ct).ConfigureAwait(false);

        if (string.Equals(lastHash, currentHash, StringComparison.Ordinal))
        {
            return Result.Success();
        }

        var syncResult = await store.SyncPermissionsAsync(permissions, ct).ConfigureAwait(false);
        if (syncResult.IsFailure)
        {
            return syncResult;
        }

        return await stateStore.UpdateHashAsync(SyncKey, currentHash, ct).ConfigureAwait(false);
    }
}

