using Microsoft.CodeAnalysis;
using VK.Tools.SourceGenerators.DependencyInjection.Models;
using VK.Tools.SourceGenerators.Extensions;

namespace VK.Tools.SourceGenerators.DependencyInjection.Emitters.Feature;

internal static class FeatureOptionsEmitter
{
    public static void Emit(SourceProductionContext ctx, FeatureTarget target)
    {
        var sb = SourceCodeBuilder.CreateWithHeader();
        sb.AppendLine("using VK.Blocks.Core;");
        sb.AppendLine();
        sb.AppendLine($"namespace {target.Options.FullNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial record {target.Options.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>The configuration section name, automatically generated by VK.Blocks.</summary>");
        sb.AppendLine($"    public static string SectionName => \"{target.Options.ComputedSectionName}\";");
        sb.AppendLine("}");

        ctx.AddSource($"{target.Options.ClassName}.Feature.g.cs", sb.ToString());
    }
}
