using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace VK.Blocks.Generators.Authentication;

internal sealed record MapperInfo(string ProviderName, string FullClassName, Location Location);

/// <summary>
/// A Source Generator that discovers and registers OAuth claims mappers directly in DI.
/// </summary>
[Generator]
public sealed class OAuthProviderMapperGenerator : IIncrementalGenerator
{
    private const string _attributeFullName = "VK.Blocks.Authentication.Features.OAuth.Mappers.OAuthProviderAttribute";

    private static readonly DiagnosticDescriptor _duplicateProviderWarning = new(
        id: "VK0001",
        title: "Duplicate OAuth Provider Mapper",
        messageFormat: "Multiple OAuth mappers found for provider '{0}'. Only '{1}' will be registered.",
        category: "VK.Blocks.Authentication",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Gather all classes decorated with [OAuthProvider]
        var mapperTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _attributeFullName,
                predicate: (node, _) => node is ClassDeclarationSyntax,
                transform: GetMapperInfo)
            .Where(m => m != null);

        // 2. Identify the current assembly name to ensure we only generate for the right project
        var assemblyName = context.CompilationProvider.Select((c, _) => c.AssemblyName);

        // 3. Generation logic - combined with assembly name
        context.RegisterSourceOutput(mapperTargets.Collect().Combine(assemblyName),
            (ctx, input) => EmitMapperExtensions(ctx, input.Left, input.Right));
    }

    private static MapperInfo? GetMapperInfo(GeneratorAttributeSyntaxContext context, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        var classSymbol = (INamedTypeSymbol)context.TargetSymbol;

        // Ensure the mapper is defined IN the current assembly to prevent capturing 
        // mappers from referenced assemblies (e.g. OIDC project capturing Core mappers)
        if (!SymbolEqualityComparer.Default.Equals(classSymbol.ContainingAssembly, context.SemanticModel.Compilation.Assembly))
        {
            return null;
        }

        var attribute = context.Attributes[0];
        if (attribute.ConstructorArguments.Length == 0)
            return null;

        var providerName = attribute.ConstructorArguments[0].Value?.ToString();
        if (string.IsNullOrWhiteSpace(providerName))
            return null;

        return new MapperInfo(providerName!, classSymbol.ToDisplayString(), context.TargetNode.GetLocation());
    }

    private static void EmitMapperExtensions(SourceProductionContext context, ImmutableArray<MapperInfo?> mappers, string? assemblyName)
    {
        // Guard: Only generate for the target project to avoid CS0234/CS0246 in other projects (Rule 11)
        if (string.IsNullOrEmpty(assemblyName) || 
            (!assemblyName!.Equals("VK.Blocks.Authentication", StringComparison.Ordinal) && 
             !assemblyName.Equals("VK.Blocks.Authentication.OpenIdConnect", StringComparison.Ordinal)))
        {
            return;
        }

        // Filter out nulls once
        var validMappers = mappers.Where(m => m != null).Cast<MapperInfo>().ToList();

        // Standardize the suffix for the filename only
        var fileSuffix = assemblyName.Replace(".", "");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using VK.Blocks.Authentication.Features.OAuth;");
        sb.AppendLine("using VK.Blocks.Authentication.Features.OAuth.Mappers;");
        sb.AppendLine();
        sb.AppendLine("namespace VK.Blocks.Authentication.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class OAuthMapperExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddGeneratedOAuthMappers(this IServiceCollection services)");
        sb.AppendLine("    {");

        if (validMappers.Count == 0)
        {
            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            context.AddSource($"OAuthMapperExtensions_{fileSuffix}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            return;
        }

        var grouped = validMappers.GroupBy(m => m.ProviderName);
        foreach (var group in grouped)
        {
            var mappersInGroup = group.ToList();
            var primary = mappersInGroup[0];

            // Generate registration for the primary mapper
            sb.AppendLine($"        services.AddKeyedScoped(typeof(IOAuthClaimsMapper), \"{primary.ProviderName}\", typeof({primary.FullClassName}));");

            // Report warnings for any duplicates found for the same provider
            if (mappersInGroup.Count > 1)
            {
                foreach (var dup in mappersInGroup.Skip(1))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        _duplicateProviderWarning,
                        dup.Location,
                        primary.ProviderName,
                        primary.FullClassName));
                }
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"OAuthMapperExtensions_{fileSuffix}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
