<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>VK.Blocks.AI.Eidos</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\VK.Blocks.Core.csproj" />
    <ProjectReference Include="..\AI\VK.Blocks.AI.csproj" />
    <ProjectReference Include="..\AI.Psyche\VK.Blocks.AI.Psyche.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Tools\SourceGenerators\VK.Tools.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
