using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using VK.Blocks.Core;

namespace VK.Blocks.AI;

/// <summary>
/// Defines the core contract for an AI Chat Engine. 
/// <para>
/// This interface is the atomic unit for text-based and multi-modal conversation.
/// Implementations are responsible for mapping VK-standard messages to provider-specific models (e.g., GPT-4, Claude).
/// </para>
/// </summary>
public interface IVKChatEngine
{
    /// <summary>
    /// Sends a list of messages to the chat engine and gets a single assistant response.
    /// </summary>
    /// <param name="messages">
    /// The conversation history. MUST contain at least one message. 
    /// The last message is typically the current user prompt.
    /// </param>
    /// <param name="args">
    /// The execution arguments (Temperature, TopP, etc.). 
    /// If null, provider-specific defaults defined in options will be used.
    /// </param>
    /// <param name="cancellationToken">The cancellation token to abort the request.</param>
    /// <returns>
    /// A <see cref="VKResult{T}"/> containing the <see cref="VKChatResponse"/> generated by the assistant.
    /// </returns>
    Task<VKResult<VKChatResponse>> SendAsync(
        IEnumerable<VKChatMessage> messages,
        VKChatArgs? args = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Sends a context payload containing messages and caching options to the chat engine.
    /// Uses Default Interface Methods (DIM) for 100% backward compatibility.
    /// </summary>
    Task<VKResult<VKChatResponse>> SendAsync(
        VKContextPayload payload,
        VKChatArgs? args = null,
        CancellationToken cancellationToken = default)
    {
        VKGuard.NotNull(payload);
        return SendAsync(payload.Messages, args, cancellationToken);
    }

    /// <summary>
    /// Sends a list of messages to the chat engine and streams the assistant response back in chunks.
    /// </summary>
    /// <param name="messages">The conversation history.</param>
    /// <param name="args">The execution arguments.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>
    /// An <see cref="IAsyncEnumerable{T}"/> of <see cref="VKResult{T}"/> chunks.
    /// </returns>
    IAsyncEnumerable<VKResult<VKChatStreamingResponse>> SendStreamingAsync(
        IEnumerable<VKChatMessage> messages,
        VKChatArgs? args = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Sends a context payload containing messages and caching options to the chat engine and streams response.
    /// Uses Default Interface Methods (DIM) for 100% backward compatibility.
    /// </summary>
    IAsyncEnumerable<VKResult<VKChatStreamingResponse>> SendStreamingAsync(
        VKContextPayload payload,
        VKChatArgs? args = null,
        CancellationToken cancellationToken = default)
    {
        VKGuard.NotNull(payload);
        return SendStreamingAsync(payload.Messages, args, cancellationToken);
    }

    /// <summary>
    /// Sends messages to the chat engine and receives a structured, type-safe response deserialized
    /// from JSON Schema-constrained LLM output.
    /// Uses Default Interface Methods (DIM) for 100% backward compatibility.
    /// </summary>
    Task<VKResult<VKStructuredChatResponse<T>>> SendStructuredAsync<T>(
        IEnumerable<VKChatMessage> messages,
        VKChatArgs? args = null,
        CancellationToken cancellationToken = default) where T : class
    {
        return Task.FromResult(
            VKResult.Failure<VKStructuredChatResponse<T>>(
                new VKError("AI.Chat.StructuredOutputNotSupported",
                    "This chat engine implementation does not support structured JSON output.")));
    }
}
