using System.Collections.Generic;
using VK.Blocks.AI.Psyche;

namespace VK.Blocks.AI.Cortex;

/// <summary>
/// Execution output payload returned from a Cortex dialogue turn.
/// Follows AP.01 (sealed record).
/// </summary>
public record VKChatTurnResult
{
    /// <summary>
    /// Gets the raw text response message generated by the model.
    /// </summary>
    public required string Content { get; init; }

    /// <summary>
    /// Gets the session identifier for this dialogue turn.
    /// </summary>
    public required VKSessionId SessionId { get; init; }

    /// <summary>
    /// Gets the trace identifier correlating this execution turn.
    /// </summary>
    public required string TraceId { get; init; }

    /// <summary>
    /// Gets the total token usage for this turn.
    /// </summary>
    public long TokensUsed { get; init; }

    /// <summary>
    /// Gets the total round-trip execution duration in milliseconds.
    /// </summary>
    public double ExecutionDurationMs { get; init; }

    /// <summary>
    /// Gets the stage-by-stage profiling metrics.
    /// </summary>
    public IReadOnlyDictionary<string, double> ProfilingMetrics { get; init; } = new Dictionary<string, double>();
}
