using Microsoft.CodeAnalysis;
using VK.Tools.SourceGenerators.Feature.Models;
using VK.Tools.SourceGenerators.Extensions;

namespace VK.Tools.SourceGenerators.Feature.Internal;

internal static class OptionsPartialEmitter
{
    public static void Emit(SourceProductionContext ctx, FeatureTarget target)
    {
        var sb = SourceCodeBuilder.CreateWithHeader();
        sb.AppendLine("using VK.Blocks.Core;");
        sb.AppendLine();
        sb.AppendLine($"namespace {target.OptionsFullNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial record {target.OptionsClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>The configuration section name, automatically generated by VK.Blocks.</summary>");
        sb.AppendLine($"    public static string SectionName => \"{target.ComputedSectionName}\";");
        sb.AppendLine("}");

        ctx.AddSource($"{target.OptionsClassName}.Feature.g.cs", sb.ToString());
    }
}
