using System;
using System.Collections.Generic;

namespace VK.Blocks.AI.Cognitive;

/// <summary>
/// Domain Reflection Entity: Represents the condensed crystallization of multiple memory traces.
/// <para>
/// Generated by the Metabolism engine during sleep/pruning cycles, a Synopsis compresses 
/// redundant Short-Term traces into a single high-value Long-Term insight. 
/// Crucially, it maintains a <see cref="Lineage"/> property to preserve enterprise auditability,
/// tracking exactly which original traces birthed this summary.
/// </para>
/// </summary>
public sealed record VKMemorySynopsis
{
    /// <summary>
    /// Gets the unique identifier for this synthesized insight.
    /// </summary>
    public required string Id { get; init; }

    /// <summary>
    /// Gets the highly compressed, reflective summary generated by the Cognitive Engine.
    /// </summary>
    public required string Summary { get; init; }

    /// <summary>
    /// Gets the lineage/bloodline of this synopsis. Contains the IDs of the original <see cref="VKMemoryTrace"/> 
    /// items that were consumed/condensed to create this summary (ensuring absolute auditability).
    /// </summary>
    public required IReadOnlyList<string> Lineage { get; init; }

    /// <summary>
    /// Gets the timestamp when this reflective summary was crystallized.
    /// </summary>
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// Gets extended structural metadata associated with this synopsis.
    /// </summary>
    public IReadOnlyDictionary<string, string> Metadata { get; init; } = new Dictionary<string, string>();
}
